# Generated by Django 4.0.4 on 2022-04-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='shop name')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('state', models.BooleanField(default=True, verbose_name='order receipt status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user name')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'List of shops',
                'ordering': ('-name',),
            },
        ),
    ]
