# Generated by Django 4.0.4 on 2022-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0002_alter_shop_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('shops', models.ManyToManyField(blank=True, related_name='categories', to='api_backend.shop', verbose_name='Shops')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'List of categories',
                'db_table': 'categories',
                'ordering': ('-name',),
            },
        ),
    ]
