# Generated by Django 4.0.4 on 2022-04-28 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, help_text='Enter contact person', max_length=50, verbose_name='contact person')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number', max_length=128, null=True, region=None, verbose_name='phone')),
                ('city', models.CharField(blank=True, help_text='Enter city name', max_length=50, verbose_name='city')),
                ('street', models.CharField(blank=True, help_text='Enter street name', max_length=100, verbose_name='street')),
                ('house', models.CharField(blank=True, max_length=15, verbose_name='house')),
                ('structure', models.CharField(blank=True, max_length=15, verbose_name='structure')),
                ('building', models.CharField(blank=True, max_length=15, verbose_name='building')),
                ('apartment', models.CharField(blank=True, max_length=15, verbose_name='apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Individual contacts',
                'db_table': 'contacts',
            },
        ),
    ]
